import type { User, Spot, Machine, FeedItem } from './types';

export const CURRENT_USER_ID = 'u1';

// デモ用の現在地（秋葉原付近）。s1/s4 は半径500m内＝投稿可、池袋/渋谷/錦糸町は圏外＝投稿不可
export const USER_LOCATION = { lat: 35.7010, lng: 139.7730 };

// デモ用：現在からの相対時刻（鮮度フィルタを安定して見せるため）
const ago = (hours: number) => new Date(Date.now() - hours * 3600 * 1000).toISOString();

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'たいよう',
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=taiyo',
    favoriteIps: ['ポケモン', 'ハイキュー!!', 'チェンソーマン'],
    bio: '推しはハイキューとポケモン。近所のガチャは大体踏破。神引き報告します',
  },
  {
    id: 'u2',
    name: 'ゆうな',
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=yuna',
    favoriteIps: ['ジョジョ', 'ポケモン'],
    bio: 'ジョジョのスタンドフィギュア集めてます。池袋・渋谷によく出没',
  },
  {
    id: 'u3',
    name: 'けんた',
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=kenta',
    favoriteIps: ['ワンピース', 'ドラゴンボール'],
    bio: 'ワンピースとドラゴンボール一筋。在庫報告まめにやってます',
  },
];

export const MOCK_SPOTS: Spot[] = [
  {
    id: 's1',
    name: 'アキバガチャ広場',
    address: '東京都千代田区外神田1-15',
    lat: 35.7022,
    lng: 139.7741,
    machineCount: 12,
    pinState: 'favorite_in_stock',
  },
  {
    id: 's2',
    name: 'ガチャガチャの森 池袋店',
    address: '東京都豊島区東池袋1-2-3',
    lat: 35.7295,
    lng: 139.7109,
    machineCount: 8,
    pinState: 'in_stock',
  },
  {
    id: 's3',
    name: 'カプコン公式ガチャコーナー',
    address: '東京都渋谷区道玄坂2-6',
    lat: 35.6595,
    lng: 139.6977,
    machineCount: 6,
    pinState: 'favorite_no_stock',
  },
  {
    id: 's4',
    name: 'ガチャポンの殿堂 秋葉原',
    address: '東京都千代田区外神田4-3-3',
    lat: 35.6993,
    lng: 139.7720,
    machineCount: 32,
    pinState: 'in_stock',
  },
  {
    id: 's5',
    name: 'イトーヨーカドー錦糸町店',
    address: '東京都墨田区江東橋4-27-14',
    lat: 35.6943,
    lng: 139.8157,
    machineCount: 4,
    pinState: 'no_stock',
  },
  {
    id: 's6',
    name: 'ラウンドワン渋谷店',
    address: '東京都渋谷区道玄坂1-20',
    lat: 35.6580,
    lng: 139.6988,
    machineCount: 5,
    pinState: 'unknown',
  },
];

export const MOCK_MACHINES: Machine[] = [
  {
    id: 'm1',
    spotId: 's1',
    seriesName: 'ポケモン ミニフィギュア vol.4',
    ipName: 'ポケモン',
    maker: 'タカラトミーアーツ',
    price: 300,
    imageUrl: 'https://picsum.photos/seed/pokemon1/200/200',
    stockStatus: 'in_stock',
    stockQuantity: 'plenty',
    lastReportedAt: '2026-05-28T09:15:00Z',
    reportCount: 4,
  },
  {
    id: 'm2',
    spotId: 's1',
    seriesName: 'ハイキュー!! アクリルスタンド 第3弾',
    ipName: 'ハイキュー!!',
    maker: 'バンダイ',
    price: 400,
    imageUrl: 'https://picsum.photos/seed/haikyuu1/200/200',
    stockStatus: 'in_stock',
    stockQuantity: 'low',
    lastReportedAt: '2026-05-28T08:30:00Z',
    reportCount: 2,
  },
  {
    id: 'm3',
    spotId: 's3',
    seriesName: 'チェンソーマン マスコットフィギュア',
    ipName: 'チェンソーマン',
    maker: 'バンプレスト',
    price: 500,
    imageUrl: 'https://picsum.photos/seed/chainsaw1/200/200',
    stockStatus: 'out_of_stock',
    lastReportedAt: '2026-05-28T07:00:00Z',
    reportCount: 3,
  },
  {
    id: 'm4',
    spotId: 's4',
    seriesName: 'ワンピース ウィーアー！フィギュア',
    ipName: 'ワンピース',
    maker: 'バンダイ',
    price: 300,
    imageUrl: 'https://picsum.photos/seed/onepiece1/200/200',
    stockStatus: 'in_stock',
    stockQuantity: 'normal',
    lastReportedAt: '2026-05-27T22:00:00Z',
    reportCount: 5,
  },
  {
    id: 'm5',
    spotId: 's2',
    seriesName: 'ジョジョの奇妙な冒険 スタンドフィギュア',
    ipName: 'ジョジョ',
    maker: 'メガハウス',
    price: 500,
    imageUrl: 'https://picsum.photos/seed/jojo1/200/200',
    stockStatus: 'in_stock',
    stockQuantity: 'normal',
    lastReportedAt: '2026-05-28T06:45:00Z',
    reportCount: 1,
  },
];

export const MOCK_FEED: FeedItem[] = [
  {
    id: 'f1',
    type: 'pull',
    userId: 'u2',
    userName: 'ゆうな',
    userAvatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=yuna',
    machine: MOCK_MACHINES[1],
    spot: MOCK_SPOTS[0],
    pull: {
      id: 'p1',
      machineId: 'm2',
      spotId: 's1',
      userId: 'u2',
      result: 'hit',
      itemName: '影山飛雄 アクリルスタンド',
      imageUrl: 'https://picsum.photos/seed/haikyuu_pull/400/500',
      memo: 'ずっと狙ってた影山引けた！！！',
      isPublic: true,
      createdAt: '2026-05-28T09:30:00Z',
    },
    likeCount: 24,
    liked: false,
    createdAt: '2026-05-28T09:30:00Z',
  },
  {
    id: 'f2',
    type: 'report',
    userId: 'u3',
    userName: 'けんた',
    userAvatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=kenta',
    machine: MOCK_MACHINES[0],
    spot: MOCK_SPOTS[0],
    report: {
      id: 'r1',
      machineId: 'm1',
      spotId: 's1',
      userId: 'u3',
      status: 'in_stock',
      quantity: 'plenty',
      createdAt: '2026-05-28T09:15:00Z',
    },
    likeCount: 8,
    liked: true,
    createdAt: ago(1.5), // 新鮮な在庫報告
  },
  {
    id: 'f3',
    type: 'pull',
    userId: 'u3',
    userName: 'けんた',
    userAvatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=kenta',
    machine: MOCK_MACHINES[3],
    spot: MOCK_SPOTS[3],
    pull: {
      id: 'p2',
      machineId: 'm4',
      spotId: 's4',
      userId: 'u3',
      result: 'duplicate',
      itemName: 'ルフィ フィギュア',
      imageUrl: 'https://picsum.photos/seed/onepiece_pull/400/500',
      memo: 'ルフィまたかぶった…3個目',
      isPublic: true,
      createdAt: '2026-05-27T21:00:00Z',
    },
    likeCount: 31,
    liked: false,
    createdAt: '2026-05-27T21:00:00Z',
  },
  {
    id: 'f4',
    type: 'pull',
    userId: 'u2',
    userName: 'ゆうな',
    userAvatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=yuna',
    machine: MOCK_MACHINES[4],
    spot: MOCK_SPOTS[1],
    pull: {
      id: 'p3',
      machineId: 'm5',
      spotId: 's2',
      userId: 'u2',
      result: 'miss',
      imageUrl: 'https://picsum.photos/seed/jojo_pull/400/500',
      memo: '吉良吉影狙いで3連爆死した',
      isPublic: true,
      createdAt: '2026-05-27T18:30:00Z',
    },
    likeCount: 47,
    liked: false,
    createdAt: '2026-05-27T18:30:00Z',
  },
  {
    id: 'f5',
    type: 'report',
    userId: 'u2',
    userName: 'ゆうな',
    userAvatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=yuna',
    machine: MOCK_MACHINES[2],
    spot: MOCK_SPOTS[2],
    report: {
      id: 'r2',
      machineId: 'm3',
      spotId: 's3',
      userId: 'u2',
      status: 'out_of_stock',
      createdAt: '2026-05-27T17:00:00Z',
    },
    likeCount: 5,
    liked: false,
    createdAt: '2026-05-27T17:00:00Z',
  },
  {
    id: 'f6',
    type: 'pull',
    userId: 'u3',
    userName: 'けんた',
    userAvatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=kenta',
    machine: MOCK_MACHINES[0],
    spot: MOCK_SPOTS[0],
    pull: {
      id: 'p4',
      machineId: 'm1',
      spotId: 's1',
      userId: 'u3',
      result: 'hit',
      itemName: 'リザードン フィギュア',
      imageUrl: 'https://picsum.photos/seed/pokemon_pull1/400/500',
      memo: '第4弾でリザードン一発！造形やばい',
      isPublic: true,
      createdAt: '2026-05-28T10:10:00Z',
    },
    likeCount: 38,
    liked: false,
    createdAt: ago(2),
  },
  {
    id: 'f7',
    type: 'pull',
    userId: 'u2',
    userName: 'ゆうな',
    userAvatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=yuna',
    machine: MOCK_MACHINES[0],
    spot: MOCK_SPOTS[3],
    pull: {
      id: 'p5',
      machineId: 'm1',
      spotId: 's4',
      userId: 'u2',
      result: 'duplicate',
      itemName: 'ピカチュウ フィギュア',
      imageUrl: 'https://picsum.photos/seed/pokemon_pull2/400/500',
      memo: 'ピカチュウ3体目…交換したい人いる？',
      isPublic: true,
      createdAt: '2026-05-28T08:50:00Z',
    },
    likeCount: 21,
    liked: false,
    createdAt: ago(4),
  },
  {
    // 古い在庫報告（鮮度フィルタで詳細から除外される例）
    id: 'f8',
    type: 'report',
    userId: 'u3',
    userName: 'けんた',
    userAvatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=kenta',
    machine: MOCK_MACHINES[0],
    spot: MOCK_SPOTS[3],
    report: {
      id: 'r3',
      machineId: 'm1',
      spotId: 's4',
      userId: 'u3',
      status: 'in_stock',
      createdAt: ago(30),
    },
    likeCount: 2,
    liked: false,
    createdAt: ago(30),
  },
  {
    // 自分（たいよう）の投稿
    id: 'f9',
    type: 'pull',
    userId: 'u1',
    userName: 'たいよう',
    userAvatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=taiyo',
    machine: MOCK_MACHINES[1],
    spot: MOCK_SPOTS[0],
    pull: {
      id: 'p6',
      machineId: 'm2',
      spotId: 's1',
      userId: 'u1',
      result: 'hit',
      itemName: '日向翔陽 アクリルスタンド',
      imageUrl: 'https://picsum.photos/seed/taiyo_pull/400/500',
      memo: '日向きた！朝イチで並んだ甲斐あった',
      isPublic: true,
      createdAt: ago(20),
    },
    likeCount: 12,
    liked: false,
    createdAt: ago(20),
  },
  {
    id: 'f10',
    type: 'report',
    userId: 'u1',
    userName: 'たいよう',
    userAvatar: 'https://api.dicebear.com/7.x/thumbs/svg?seed=taiyo',
    machine: MOCK_MACHINES[0],
    spot: MOCK_SPOTS[0],
    report: {
      id: 'r4',
      machineId: 'm1',
      spotId: 's1',
      userId: 'u1',
      status: 'in_stock',
      createdAt: ago(50),
    },
    likeCount: 4,
    liked: false,
    createdAt: ago(50),
  },
];

// ── 通知 ──
// restock（在庫復活）が主役＝BeReal風の一撃。お気に入りIP（ポケモン/ワンピース）に紐づく
export type NotificationType = 'restock' | 'release' | 'upcoming' | 'community';

export interface AppNotification {
  id: string;
  type: NotificationType;
  title: string;
  body: string;
  gachaId?: string;
  createdAt: string;
  read: boolean;
}

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n1', type: 'restock',
    title: '在庫が復活！',
    body: '渋谷で「ポケモン ミニフィギュア vol.5」が今、引けます',
    gachaId: 'g1', createdAt: '2026-06-01T09:40:00Z', read: false,
  },
  {
    id: 'n2', type: 'release',
    title: '発売中',
    body: '「ワンピース ガチャ 麦わらver.」が発売中。近くにあるかチェック',
    gachaId: 'g4', createdAt: '2026-06-01T07:00:00Z', read: false,
  },
  {
    id: 'n3', type: 'upcoming',
    title: '来週発売',
    body: '「ちいかわ もこもこマスコット」が6月第1週スタート。お知らせをオンにしました',
    gachaId: 'g9', createdAt: '2026-05-31T20:00:00Z', read: true,
  },
  {
    id: 'n4', type: 'community',
    title: 'みんなの動き',
    body: 'お気に入りのポケモンを今週243人が引いています',
    gachaId: 'g6', createdAt: '2026-05-31T10:00:00Z', read: true,
  },
];
